### PR TITLE
German localization

### PR DESCRIPTION
**Pull request by staticalliam7**
localization speedrun

### CODE REVIEW

**Comment by zer0Kerbal** [comment]
am hesitant to include any changes to .csproj - bad taste in my mouth last time (not you) did.

**Comment by staticalliam7** [comment]
ohno what did you do last time?

**Comment by zer0Kerbal** [comment]
- closes #71 
- closes #87 
- updates #55

**Comment by zer0Kerbal** [comment]
> ohno what did you do last time?

somebody pushed changes to my repo - which changed the .csproj and .sln - and it cause a massive mess. Fortunately I make backup copies now. *chuckle*

Any way for you to remove the .csproj and readme.md changes? I normally do that - and most is already there on this branch.

**Review by zer0Kerbal — APPROVED** [review]

**Comment by staticalliam7** [comment]
Yeah, I'll see what I can do

**Comment by staticalliam7** [comment]
Either I'm just unskilled, or I can't revert those changes...

**Comment by zer0Kerbal** [comment]
I'm being nitpicky - 

> Either I'm just unskilled, or I can't revert those changes...

all good then. 🥇

**Comment by staticalliam7** [comment]
I can just replace it if the stuff in release branch is valid

**Comment by zer0Kerbal** [comment]
was able to fix it (I believe) knocking on 🌲

**Pull request merged**
