### PR TITLE
Quadruple translate

### PR DESCRIPTION
**Pull request by staticalliam7**
Italian, Russian, Polish, and French

### CODE REVIEW

**Comment by staticalliam7** [comment]
German translation is a duplicate since my fork isn't on the release branch

**Review by zer0Kerbal — APPROVED** [review]

**Comment by staticalliam7** [comment]
this is what I thought when I saw the other localization stuff

**Comment by staticalliam7** [comment]
@zer0Kerbal Gentle reminder to update the readme to show currently localized languages

**Comment by zer0Kerbal** [comment]
> @zer0Kerbal Gentle reminder to update the readme to show currently localized languages

thank you. :D [#89 ](https://github.com/zer0Kerbal/MoarKerbals/issues/89)

**Pull request merged**
