### PR TITLE
Espanol Localization

### PR DESCRIPTION
**Pull request by staticalliam7**
:)

### CODE REVIEW

**Review by staticalliam7 — COMMENTED** [review]
i did a great job obviously

**Comment by zer0Kerbal** [comment]
> i did a great job obviously

thank you @staticalliam7 !

**Comment by staticalliam7** [comment]
wait so I won't show up as a contributor unless I commit directly?

**Comment by zer0Kerbal** [comment]
the commit (if I understand correctly) won't show up until the branch is merged into the master branch.

**Comment by staticalliam7** [comment]
👍

**Pull request merged**
